// Generated by CoffeeScript 1.3.3
(function() {
  var withSiteResponse;

  withSiteResponse = function(request, sender, sendResponse, site) {
    if (request.action === 'getOpts') {
      sendResponse(site && site.toJSON());
    }
    if (request.action === 'showPageAction') {
      chrome.pageAction.show(sender.tab.id);
    }
    if (request.action === 'toggleSite') {
      return chrome.tabs.getSelected(function(tab) {
        var l;
        l = document.createElement('a');
        l.href = tab.url;
        site = Sites.getSiteByDomain(l.hostname);
        if (site) {
          site.set('enabled', request.enabled);
          site.save();
        }
        return chrome.tabs.executeScript(tab.id, {
          code: 'location.reload()'
        }, function() {});
      });
    }
  };

  chrome.extension.onMessage.addListener(function(request, sender, sendResponse) {
    var site;
    if (request.domain) {
      site = Sites.getSiteByDomain(request.domain);
      withSiteResponse(request, sender, sendResponse, site);
    } else {
      chrome.tabs.getSelected(function(tab) {
        var l;
        l = document.createElement('a');
        l.href = tab.url;
        site = Sites.getSiteByDomain(l.hostname);
        return withSiteResponse(request, sender, sendResponse, site);
      });
    }
    return true;
  });

}).call(this);
