// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    chrome.extension.sendMessage({
      action: 'getOpts'
    }, function(site) {
      if (site.enabled === void 0 || site.enabled) {
        return $('#checkbox_enabled').attr('checked', 'checked');
      }
    });
    $('#checkbox_enabled').click(function() {
      if ($('#checkbox_enabled').is(':checked')) {
        return chrome.extension.sendMessage({
          action: 'toggleSite',
          enabled: true
        });
      } else {
        return chrome.extension.sendMessage({
          action: 'toggleSite',
          enabled: false
        });
      }
    });
    return $('#optionslink').click(function() {
      return chrome.tabs.create({
        url: "options.html"
      });
    });
  });

}).call(this);
