// Generated by CoffeeScript 1.3.3
(function() {
  var SiteCollection, SiteModel, Sites,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SiteModel = (function(_super) {

    __extends(SiteModel, _super);

    function SiteModel() {
      return SiteModel.__super__.constructor.apply(this, arguments);
    }

    SiteModel.prototype.getOpts = function() {
      var json;
      json = JSON.stringify(this.get('opts'));
      return json;
    };

    return SiteModel;

  })(Backbone.Model);

  SiteCollection = (function(_super) {

    __extends(SiteCollection, _super);

    function SiteCollection() {
      return SiteCollection.__super__.constructor.apply(this, arguments);
    }

    SiteCollection.prototype.model = SiteModel;

    SiteCollection.prototype.localStorage = new Backbone.LocalStorage("JKSites");

    return SiteCollection;

  })(Backbone.Collection);

  Sites = new SiteCollection();

}).call(this);
